// ====================================================
// generate_events.js
// Run with Node.js to create events_generated.js
// ====================================================

const fs = require('fs');
const path = require('path');

// Load source data
// In a real scenario, these would be loaded from separate files or a database.
// For now, we will define them here based on the documentation, or load from a source file if we create one.
// Let's assume we import them from a data file for cleaner code.
const { sponsoredEvents, tourismEvents } = require('../data/events_source.js');

// ---------- Helper functions ----------
function determineExperienceType(event) {
    // Priority order
    if (event.guardianRequired || (event.ageGroup && event.ageGroup !== 'adult')) {
        return 'three_way_handshake';
    }
    if (event.entryFee > 0) {
        return 'monetization_waiver';
    }
    if (event.scoutAttendance || event.talentIdentification) {
        return 'sports_cv_sync';
    }
    if (event.activityState === 'recruiting' || event.matchMaking) {
        return 'proposed_milestone';
    }
    if (event.category === 'social_gathering' && !event.requiresForm) {
        return 'direct_connect';
    }
    if (event.capacity === 'unlimited' && event.entryFee === 0) {
        return 'one_tap';
    }
    // Default
    return 'event_lab_form';
}

function addExperienceFields(event) {
    const expType = determineExperienceType(event);
    const enriched = {
        ...event,
        experienceType: expType,
        // Additional fields that may be needed by the expansion module
        guardianRequired: event.guardianRequired || (event.ageGroup && event.ageGroup !== 'adult') || false,
        capacity: event.capacity || (event.participants && event.participants.totalTeams ? event.participants.totalTeams : 'unlimited'),
        formFields: event.formFields || [], // to be populated later if needed
        milestoneCurrent: event.milestoneCurrent || 0,
        milestoneTarget: event.milestoneTarget || (event.participants && event.participants.totalTeams ? event.participants.totalTeams : 10),
        whatsappLink: event.whatsappLink || `https://wa.me/267${Math.floor(Math.random() * 10000000)}?text=I'm%20interested%20in%20${encodeURIComponent(event.eventName)}`,
        scoutEvent: event.scoutAttendance || false,
        entryFee: event.entryFee || 0,
        villageWaiver: event.villageWaiver || (event.regionCode && ['KG', 'GH', 'NW'].includes(event.regionCode)) // example
    };
    return enriched;
}

// ---------- Normalize field names ----------
const normalizedSponsored = sponsoredEvents.map(e => ({
    eventID: e.eventID,
    eventName: e.eventName,
    sponsor: e.sponsor,
    startDate: e.startDate,
    endDate: e.endDate,
    venue: e.venue ? e.venue.primary : (e.venueName || 'TBD'),
    village: e.village_town || e.region,
    district: e.regionCode || e.district || 'Unknown',
    category: e.category || e.botswana_tourism_category || e.activityType,
    ageGroup: e.ageGroup || 'adult',
    entryFee: e.entryFee || 0,
    capacity: (e.participants && e.participants.totalTeams) || e.capacity || 100,
    activityState: e.activityState || 'upcoming',
    scoutAttendance: e.scoutAttendance || false,
    talentIdentification: e.talentIdentification || false,
    guardianRequired: e.guardianRequired || false,
    requiresForm: e.requiresForm !== undefined ? e.requiresForm : true,
    matchMaking: false,
    villageWaiver: e.villageWaiver || false,
    description: e.description || e.tagline || '',
}));

const normalizedTourism = tourismEvents.map(e => ({
    eventID: e.event_id,
    eventName: e.event_name,
    sponsor: e.sponsor || null,
    startDate: e.start_date,
    endDate: e.end_date || e.start_date,
    venue: e.venue_name || e.village_town,
    village: e.village_town,
    district: e.district,
    category: e.mizano_category || e.botswana_tourism_category,
    ageGroup: e.ageGroup || (e.botswana_tourism_category === 'Lifestyle & Entertainment' ? 'adult' : 'mixed'),
    entryFee: e.entryFee || 0,
    capacity: e.capacity || (e.estimated_attendance || 100),
    activityState: e.activity_state || 'upcoming',
    scoutAttendance: false,
    talentIdentification: false,
    guardianRequired: false,
    requiresForm: e.requiresForm !== undefined ? e.requiresForm : (e.mizano_event_type !== 'social_gathering'),
    matchMaking: false,
    villageWaiver: e.villageWaiver || false,
    description: e.description || '',
}));

// ---------- Combine and enrich ----------
const allEvents = [...normalizedSponsored, ...normalizedTourism];
const enrichedEvents = allEvents.map(addExperienceFields);

// ---------- Output as JS file ----------
const fileContent = `// events_generated.js
// Generated by generate_events.js
window.MIZANO_DATA = window.MIZANO_DATA || {};
window.MIZANO_DATA.events = ${JSON.stringify(enrichedEvents, null, 2)};`;

// Write to file
const outputPath = path.join(__dirname, '../data/events_generated.js');
fs.writeFileSync(outputPath, fileContent);

console.log(`Successfully generated events to ${outputPath}`);
